"""create zodiacs table

Revision ID: fc276269e491
Revises: 
Create Date: 2023-06-30 23:49:48.874339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc276269e491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zodiac_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_date', sa.Integer(), nullable=False),
    sa.Column('last_date', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zodiacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zodiac_name', sa.String(), nullable=True),
    sa.Column('id_zodiac', sa.Integer(), nullable=False),
    sa.Column('date_bth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_zodiac'], ['zodiac_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zodiacs')
    op.drop_table('zodiac_base')
    # ### end Alembic commands ###
